spring.application.name=app
#spring.datasource.url=jdbc:mysql://localhost:3306/chatdb
#
#spring.datasource.username=root
#spring.datasource.password=Injam123

spring.datasource.url=postgresql://ifun123:afRLttcBJ3xU7LQlvRqZmNBicFypXEUC@dpg-d8nqa2rsq97s73bn3040-a/chatdb_u43o
spring.datasource.username= ifun123
spring.datasource.password=afRLttcBJ3xU7LQlvRqZmNBicFypXEUC

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver